// Generated by CoffeeScript 1.12.3
(function() {
  var testData;

  testData = [
    {
      'id': 'G123456A',
      cardType: 'hkid',
      expect: true
    }, {
      'id': 'A5555550',
      cardType: 'hkid',
      expect: true
    }, {
      'id': 'AB9876542',
      cardType: 'hkid',
      expect: true
    }
  ];

  if ((typeof module !== "undefined" && module !== null) && module.exports) {
    module.exports = testData;
  }

  if (typeof window !== "undefined" && window !== null) {
    window.validid = testData;
  }

}).call(this);
